authors = ["Michael Schlottke-Lakemper <michael@sloede.com>"]
name = "P4est"
uuid = "7d669430-f675-4ae7-b43e-fab78ec5a902"
version = "0.3.3-pre"

[compat]
CEnum = "0.4"
MPI = "0.20"
P4est_jll = "~2.8"
Preferences = "1"
Reexport = "0.2, 1.0"
julia = "1.6"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
P4est_jll = "6b5a15aa-cf52-5330-8376-5e5d90283449"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
