name = "P4est"
uuid = "7d669430-f675-4ae7-b43e-fab78ec5a902"
authors = ["Michael Schlottke-Lakemper <michael@sloede.com>"]
version = "0.3.0-prev"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
P4est_jll = "6b5a15aa-cf52-5330-8376-5e5d90283449"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
CBinding = "0.9.2"
MPI = "0.15, 0.16, 0.18, 0.19"
P4est_jll = "~2.8"
Reexport = "0.2, 1.0"
julia = "1.6"
