name = "P4est"
uuid = "7d669430-f675-4ae7-b43e-fab78ec5a902"
authors = ["Michael Schlottke-Lakemper <michael@sloede.com>"]
version = "0.1.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
P4est_jll = "6b5a15aa-cf52-5330-8376-5e5d90283449"
