[deps]
CBindingGen = "308a6e0c-0495-45e1-b1ab-67fb455a0d77"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
P4est_jll = "6b5a15aa-cf52-5330-8376-5e5d90283449"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
CBindingGen = "0.4"
