[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
P4est_jll = "6b5a15aa-cf52-5330-8376-5e5d90283449"

[compat]
CEnum = "0.4"
Clang = "0.17.7"
MPI = "0.20"
P4est_jll = "2.8"
